---
- name: manage docker
  hosts: group1
  become: true
  vars:
    drupal_port: 8026
  tasks:
  - name: Install docker and some dependencies
    apt:
      name: python3-pip, docker-ce
      state: present
  - name: Start docker service
    service:
      name: docker
      state: started
  - name: Install docker python module
    pip:
      name: docker
  - name: Create Drupal container
    docker_container:
      name: drupal
      image: drupal
      state: started
      ports:
        - "{{ drupal_port }}:80"
      volumes:
        - drupal_modules:/var/www/html/modules
        - drupal_profiles:/var/www/html/profiles
        - drupal_themes:/var/www/html/themes
        - drupal_sites:/var/www/html/sites
