---
- name: manage httpd.conf
  hosts: group1
  become: true
  tasks:
  - name: Copy web 8080 configuration file
    copy:
      src: web-8080.conf
      dest: /etc/nginx/sites-enabled/
    when: has_8080
    notify:
      - reload_nginx
  handlers:
  - name: reload_nginx
    service:
      name: nginx
      state: reloaded
  
